name: Setup Bench

on:
  workflow_call:
    outputs:
      bench-dir:
        description: "Path to bench"
        value: ${{ jobs.setup.outputs.bench-dir }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      bench-dir: ${{ steps.set-bench-dir.outputs.bench-dir }}

    services:
      redis-cache:
        image: redis:alpine
        ports: [13000:6379]
      redis-queue:
        image: redis:alpine
        ports: [11000:6379]
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports: [3306:3306]
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Install MariaDB Client
        run: |
          sudo apt update
          sudo apt-get install mariadb-client

      - name: Setup Bench
        run: |
          pip install frappe-bench
          bench init --skip-redis-config-generation --skip-assets --python "$(which python)" ~/frappe-bench
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

      - name: Set Bench Dir
        id: set-bench-dir
        run: echo "bench-dir=/home/runner/frappe-bench" >> $GITHUB_OUTPUT
