name: Run Unit Tests

on:
  workflow_call:
    inputs:
      bench-dir:
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run Unit Tests
        working-directory: ${{ inputs.bench-dir }}
        run: |
          bench run-tests --app frappe_types
