# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/_setup.yml

  unit-tests:
    needs: setup
    uses: ./.github/workflows/_unit-tests.yml
    with:
      bench-dir: ${{ needs.setup.outputs.bench-dir }}

  ui-tests:
    needs: setup
    uses: ./.github/workflows/_ui-tests.yml
    with:
      bench-dir: ${{ needs.setup.outputs.bench-dir }}
