name: UI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: UI Tests
    uses: frappe/frappe/.github/workflows/_base-ui-tests.yml@develop
    env:
      FRAPPE_GH_ORG: frappe
    with:
      parallel-runs: 3